{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "history_visible": true,
      "authorship_tag": "ABX9TyPlG4PRMakS2bq2h3UfrkIU",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/galo132171/trabalho-inf-14-rpzd/blob/main/compara%C3%A7%C3%A3o%20dos%20modelos%20utilizados\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "aula 1\n"
      ],
      "metadata": {
        "id": "ioq48xFNMEP3"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import pandas as pd\n",
        "from abc import ABC, abstractmethod\n",
        "\n",
        "# 1. ABSTRAÇÃO E ENCAPSULAMENTO DA ENTIDADE VEÍCULO\n",
        "class VeiculoBase(ABC):\n",
        "    \"\"\"Classe abstrata base para os veículos.\"\"\"\n",
        "\n",
        "    def __init__(self, marca: str, modelo: str, ano: int, avaliacao: float):\n",
        "        self._marca = marca\n",
        "        self._modelo = modelo\n",
        "        self._ano = ano\n",
        "        self._avaliacao = avaliacao\n",
        "\n",
        "    @abstractmethod\n",
        "    def exibir_resumo(self) -> None:\n",
        "        pass\n",
        "\n",
        "\n",
        "class Veiculo(VeiculoBase):\n",
        "    \"\"\"\n",
        "    Classe que encapsula totalmente os dados e comportamentos dos veículos\n",
        "    unificando dados dos arquivos de desempenho, segurança e custo-benefício.\n",
        "    \"\"\"\n",
        "    def __init__(\n",
        "        self,\n",
        "        marca: str,\n",
        "        modelo: str,\n",
        "        ano: int,\n",
        "        avaliacao: float,\n",
        "        aceleracao_ms2: float,\n",
        "        frenagem_ms2: float,\n",
        "        sistema_frenagem: str,\n",
        "        sistemas_auxiliares: str,\n",
        "        notas_cb: dict,\n",
        "        preco: float = 0.0\n",
        "    ):\n",
        "        super().__init__(marca, modelo, ano, avaliacao)\n",
        "\n",
        "        # Encapsulamento dos atributos privados\n",
        "        self.__aceleracao_ms2 = aceleracao_ms2\n",
        "        self.__frenagem_ms2 = frenagem_ms2\n",
        "        self.__sistema_frenagem = sistema_frenagem\n",
        "        self.__sistemas_auxiliares = sistemas_auxiliares\n",
        "        self.__notas_cb = notas_cb  # {desempenho, economia, manutencao, conforto}\n",
        "        self.__preco = preco\n",
        "\n",
        "    # --- GETTERS E SETTERS (Interface Pública Encapsulada) ---\n",
        "    @property\n",
        "    def modelo(self) -> str:\n",
        "        return self._modelo\n",
        "\n",
        "    @property\n",
        "    def marca(self) -> str:\n",
        "        return self._marca\n",
        "\n",
        "    @property\n",
        "    def ano(self) -> int:\n",
        "        return self._ano\n",
        "\n",
        "    @property\n",
        "    def avaliacao(self) -> float:\n",
        "        return self._avaliacao\n",
        "\n",
        "    @property\n",
        "    def preco(self) -> float:\n",
        "        return self.__preco\n",
        "\n",
        "    @preco.setter\n",
        "    def preco(self, novo_preco: float) -> None:\n",
        "        if novo_preco > 0:\n",
        "            self.__preco = novo_preco\n",
        "        else:\n",
        "            print(\"[Erro] O preço deve ser um valor positivo!\")\n",
        "\n",
        "    # --- REGRAS DE NEGÓCIO E CÁLCULOS ENCAPSULADOS ---\n",
        "    def calcular_tempo_0_100(self) -> float:\n",
        "        \"\"\"Calcula o tempo de 0 a 100 km/h com base na aceleração em m/s².\"\"\"\n",
        "        if self.__aceleracao_ms2 > 0:\n",
        "            return (100 / 3.6) / self.__aceleracao_ms2\n",
        "        return 0.0\n",
        "\n",
        "    def calcular_custo_beneficio(self) -> float:\n",
        "        \"\"\"Calcula a pontuação de custo-benefício com base na média das notas e preço.\"\"\"\n",
        "        if self.__preco <= 0:\n",
        "            return 0.0\n",
        "        media_notas = sum(self.__notas_cb.values()) / len(self.__notas_cb)\n",
        "        return (media_notas * 10000) / self.__preco\n",
        "\n",
        "    def obter_dados_dict(self) -> dict:\n",
        "        \"\"\"Retorna dicionário unificado com todos os atributos encapsulados.\"\"\"\n",
        "        media_cb = sum(self.__notas_cb.values()) / len(self.__notas_cb)\n",
        "        return {\n",
        "            \"Marca\": self._marca,\n",
        "            \"Modelo\": self._modelo,\n",
        "            \"Ano\": self._ano,\n",
        "            \"Avaliação (0-5)\": self._avaliacao,\n",
        "            \"Aceleração (m/s²)\": self.__aceleracao_ms2,\n",
        "            \"Tempo 0-100km/h (s)\": round(self.calcular_tempo_0_100(), 2),\n",
        "            \"Frenagem (m/s²)\": self.__frenagem_ms2,\n",
        "            \"Tipo de Frenagem\": self.__sistema_frenagem,\n",
        "            \"Sistemas Auxiliares\": self.__sistemas_auxiliares,\n",
        "            \"Nota Média C.B.\": round(media_cb, 1),\n",
        "            \"Preço (R$)\": self.__preco,\n",
        "            \"Custo-Benefício\": round(self.calcular_custo_beneficio(), 4)\n",
        "        }\n",
        "\n",
        "    def exibir_resumo(self) -> None:\n",
        "        print(f\"\\n==============================\")\n",
        "        print(f\"CARRO: {self._modelo} ({self._marca})\")\n",
        "        print(f\"Ano: {self._ano} | Avaliação: {self._avaliacao}/5.0\")\n",
        "        print(f\"Aceleração: {self.__aceleracao_ms2} m/s² (0-100 km/h: {self.calcular_tempo_0_100():.2f}s)\")\n",
        "        print(f\"Frenagem: {self.__sistema_frenagem} ({self.__frenagem_ms2} m/s²)\")\n",
        "        print(f\"Sistemas Auxiliares: {self.__sistemas_auxiliares}\")\n",
        "\n",
        "\n",
        "# 2. GERENCIADOR DO SISTEMA DE COMPARAÇÃO\n",
        "class SistemaComparadorVeiculos:\n",
        "    \"\"\"Gerencia o repositório de veículos e executa análises comparativas.\"\"\"\n",
        "\n",
        "    def __init__(self):\n",
        "        self.__frota = {}\n",
        "\n",
        "    def adicionar_veiculo(self, veiculo: Veiculo) -> None:\n",
        "        self.__frota[veiculo.modelo.lower()] = veiculo\n",
        "\n",
        "    def buscar_veiculo(self, nome: str) -> Veiculo:\n",
        "        return self.__frota.get(nome.strip().lower(), None)\n",
        "\n",
        "    def gerar_dataframe(self) -> pd.DataFrame:\n",
        "        dados = [v.obter_dados_dict() for v in self.__frota.values()]\n",
        "        return pd.DataFrame(dados)\n",
        "\n",
        "    def exibir_ranking_custo_beneficio(self) -> None:\n",
        "        lista_veiculos = list(self.__frota.values())\n",
        "        lista_veiculos.sort(key=lambda x: x.calcular_custo_beneficio(), reverse=True)\n",
        "\n",
        "        print(\"\\n=== RANKING DE CUSTO-BENEFÍCIO ===\")\n",
        "        for i, r in enumerate(lista_veiculos, 1):\n",
        "            cb = r.calcular_custo_beneficio()\n",
        "            print(f\"{i}º - {r.modelo} (CB: {cb:.4f} | Preço: R$ {r.preco:,.2f})\")\n",
        "\n",
        "\n",
        "# --- DEMONSTRAÇÃO E EXECUÇÃO NO COLAB ---\n",
        "if __name__ == \"__main__\":\n",
        "    # Inicialização da base de dados com as informações integradas dos arquivos\n",
        "    sistema = SistemaComparadorVeiculos()\n",
        "\n",
        "    v1 = Veiculo(\"Honda\", \"Civic\", 2022, 4.8, 6.5, 9.0, \"ABS e freios a disco\",\n",
        "                 \"Controle de estabilidade e assistência de frenagem\",\n",
        "                 {\"desempenho\": 7, \"economia\": 8, \"manutencao\": 8, \"conforto\": 8}, preco=140000)\n",
        "\n",
        "    v2 = Veiculo(\"RAM\", \"Dodge Ram\", 2023, 4.6, 5.0, 7.0, \"ABS e freios a disco\",\n",
        "                 \"Controle de estabilidade e assistência de frenagem\",\n",
        "                 {\"desempenho\": 10, \"economia\": 3, \"manutencao\": 4, \"conforto\": 9}, preco=450000)\n",
        "\n",
        "    v3 = Veiculo(\"Fiat\", \"Palio\", 2016, 4.1, 2.0, 6.0, \"Sistema ABS (dependendo da versão)\",\n",
        "                 \"Controle de estabilidade (dependendo da versão)\",\n",
        "                 {\"desempenho\": 4, \"economia\": 10, \"manutencao\": 9, \"conforto\": 5}, preco=35000)\n",
        "\n",
        "    v4 = Veiculo(\"Ferrari\", \"Ferrari\", 2020, 4.9, 10.0, 13.0, \"Freios de alto desempenho\",\n",
        "                 \"ABS, controle de estabilidade e assistência eletrônica\",\n",
        "                 {\"desempenho\": 10, \"economia\": 1, \"manutencao\": 2, \"conforto\": 10}, preco=3500000)\n",
        "\n",
        "    for v in [v1, v2, v3, v4]:\n",
        "        sistema.adicionar_veiculo(v)\n",
        "\n",
        "    # 1. Exibir Resumos Individuais\n",
        "    print(\"=== RESUMO DOS VEÍCULOS (ENCAPSULADO) ===\")\n",
        "    for nome in [\"civic\", \"dodge ram\", \"palio\", \"ferrari\"]:\n",
        "        carro = sistema.buscar_veiculo(nome)\n",
        "        if carro:\n",
        "            carro.exibir_resumo()\n",
        "\n",
        "    # 2. Exibição Tabular em DataFrame do Pandas\n",
        "    print(\"\\n=== COMPARATIVO EM DATAFRAME ===\")\n",
        "    df = sistema.gerar_dataframe()\n",
        "    display(df)\n",
        "\n",
        "    # 3. Ranking de Custo-Benefício\n",
        "    sistema.exibir_ranking_custo_beneficio()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "9pvAEq4udyTf",
        "outputId": "c72cf70b-9421-4fc5-a9e0-e946e7cd6147"
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "=== RESUMO DOS VEÍCULOS (ENCAPSULADO) ===\n",
            "\n",
            "==============================\n",
            "CARRO: Civic (Honda)\n",
            "Ano: 2022 | Avaliação: 4.8/5.0\n",
            "Aceleração: 6.5 m/s² (0-100 km/h: 4.27s)\n",
            "Frenagem: ABS e freios a disco (9.0 m/s²)\n",
            "Sistemas Auxiliares: Controle de estabilidade e assistência de frenagem\n",
            "\n",
            "==============================\n",
            "CARRO: Dodge Ram (RAM)\n",
            "Ano: 2023 | Avaliação: 4.6/5.0\n",
            "Aceleração: 5.0 m/s² (0-100 km/h: 5.56s)\n",
            "Frenagem: ABS e freios a disco (7.0 m/s²)\n",
            "Sistemas Auxiliares: Controle de estabilidade e assistência de frenagem\n",
            "\n",
            "==============================\n",
            "CARRO: Palio (Fiat)\n",
            "Ano: 2016 | Avaliação: 4.1/5.0\n",
            "Aceleração: 2.0 m/s² (0-100 km/h: 13.89s)\n",
            "Frenagem: Sistema ABS (dependendo da versão) (6.0 m/s²)\n",
            "Sistemas Auxiliares: Controle de estabilidade (dependendo da versão)\n",
            "\n",
            "==============================\n",
            "CARRO: Ferrari (Ferrari)\n",
            "Ano: 2020 | Avaliação: 4.9/5.0\n",
            "Aceleração: 10.0 m/s² (0-100 km/h: 2.78s)\n",
            "Frenagem: Freios de alto desempenho (13.0 m/s²)\n",
            "Sistemas Auxiliares: ABS, controle de estabilidade e assistência eletrônica\n",
            "\n",
            "=== COMPARATIVO EM DATAFRAME ===\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "     Marca     Modelo   Ano  Avaliação (0-5)  Aceleração (m/s²)  \\\n",
              "0    Honda      Civic  2022              4.8                6.5   \n",
              "1      RAM  Dodge Ram  2023              4.6                5.0   \n",
              "2     Fiat      Palio  2016              4.1                2.0   \n",
              "3  Ferrari    Ferrari  2020              4.9               10.0   \n",
              "\n",
              "   Tempo 0-100km/h (s)  Frenagem (m/s²)                    Tipo de Frenagem  \\\n",
              "0                 4.27              9.0                ABS e freios a disco   \n",
              "1                 5.56              7.0                ABS e freios a disco   \n",
              "2                13.89              6.0  Sistema ABS (dependendo da versão)   \n",
              "3                 2.78             13.0           Freios de alto desempenho   \n",
              "\n",
              "                                 Sistemas Auxiliares  Nota Média C.B.  \\\n",
              "0  Controle de estabilidade e assistência de fren...              7.8   \n",
              "1  Controle de estabilidade e assistência de fren...              6.5   \n",
              "2    Controle de estabilidade (dependendo da versão)              7.0   \n",
              "3  ABS, controle de estabilidade e assistência el...              5.8   \n",
              "\n",
              "   Preço (R$)  Custo-Benefício  \n",
              "0      140000           0.5536  \n",
              "1      450000           0.1444  \n",
              "2       35000           2.0000  \n",
              "3     3500000           0.0164  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-dab53ddc-420d-4b1c-9a43-b10b758c336b\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Marca</th>\n",
              "      <th>Modelo</th>\n",
              "      <th>Ano</th>\n",
              "      <th>Avaliação (0-5)</th>\n",
              "      <th>Aceleração (m/s²)</th>\n",
              "      <th>Tempo 0-100km/h (s)</th>\n",
              "      <th>Frenagem (m/s²)</th>\n",
              "      <th>Tipo de Frenagem</th>\n",
              "      <th>Sistemas Auxiliares</th>\n",
              "      <th>Nota Média C.B.</th>\n",
              "      <th>Preço (R$)</th>\n",
              "      <th>Custo-Benefício</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>Honda</td>\n",
              "      <td>Civic</td>\n",
              "      <td>2022</td>\n",
              "      <td>4.8</td>\n",
              "      <td>6.5</td>\n",
              "      <td>4.27</td>\n",
              "      <td>9.0</td>\n",
              "      <td>ABS e freios a disco</td>\n",
              "      <td>Controle de estabilidade e assistência de fren...</td>\n",
              "      <td>7.8</td>\n",
              "      <td>140000</td>\n",
              "      <td>0.5536</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>RAM</td>\n",
              "      <td>Dodge Ram</td>\n",
              "      <td>2023</td>\n",
              "      <td>4.6</td>\n",
              "      <td>5.0</td>\n",
              "      <td>5.56</td>\n",
              "      <td>7.0</td>\n",
              "      <td>ABS e freios a disco</td>\n",
              "      <td>Controle de estabilidade e assistência de fren...</td>\n",
              "      <td>6.5</td>\n",
              "      <td>450000</td>\n",
              "      <td>0.1444</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>Fiat</td>\n",
              "      <td>Palio</td>\n",
              "      <td>2016</td>\n",
              "      <td>4.1</td>\n",
              "      <td>2.0</td>\n",
              "      <td>13.89</td>\n",
              "      <td>6.0</td>\n",
              "      <td>Sistema ABS (dependendo da versão)</td>\n",
              "      <td>Controle de estabilidade (dependendo da versão)</td>\n",
              "      <td>7.0</td>\n",
              "      <td>35000</td>\n",
              "      <td>2.0000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>Ferrari</td>\n",
              "      <td>Ferrari</td>\n",
              "      <td>2020</td>\n",
              "      <td>4.9</td>\n",
              "      <td>10.0</td>\n",
              "      <td>2.78</td>\n",
              "      <td>13.0</td>\n",
              "      <td>Freios de alto desempenho</td>\n",
              "      <td>ABS, controle de estabilidade e assistência el...</td>\n",
              "      <td>5.8</td>\n",
              "      <td>3500000</td>\n",
              "      <td>0.0164</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-dab53ddc-420d-4b1c-9a43-b10b758c336b')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-dab53ddc-420d-4b1c-9a43-b10b758c336b button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-dab53ddc-420d-4b1c-9a43-b10b758c336b');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "  <div id=\"id_312d31df-403c-4c06-b9e6-cea849ed32cf\">\n",
              "    <style>\n",
              "      .colab-df-generate {\n",
              "        background-color: #E8F0FE;\n",
              "        border: none;\n",
              "        border-radius: 50%;\n",
              "        cursor: pointer;\n",
              "        display: none;\n",
              "        fill: #1967D2;\n",
              "        height: 32px;\n",
              "        padding: 0 0 0 0;\n",
              "        width: 32px;\n",
              "      }\n",
              "\n",
              "      .colab-df-generate:hover {\n",
              "        background-color: #E2EBFA;\n",
              "        box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "        fill: #174EA6;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate {\n",
              "        background-color: #3B4455;\n",
              "        fill: #D2E3FC;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate:hover {\n",
              "        background-color: #434B5C;\n",
              "        box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "        filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "        fill: #FFFFFF;\n",
              "      }\n",
              "    </style>\n",
              "    <button class=\"colab-df-generate\" onclick=\"generateWithVariable('df')\"\n",
              "            title=\"Generate code using this dataframe.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M7,19H8.4L18.45,9,17,7.55,7,17.6ZM5,21V16.75L18.45,3.32a2,2,0,0,1,2.83,0l1.4,1.43a1.91,1.91,0,0,1,.58,1.4,1.91,1.91,0,0,1-.58,1.4L9.25,21ZM18.45,9,17,7.55Zm-12,3A5.31,5.31,0,0,0,4.9,8.1,5.31,5.31,0,0,0,1,6.5,5.31,5.31,0,0,0,4.9,4.9,5.31,5.31,0,0,0,6.5,1,5.31,5.31,0,0,0,8.1,4.9,5.31,5.31,0,0,0,12,6.5,5.46,5.46,0,0,0,6.5,12Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "    <script>\n",
              "      (() => {\n",
              "      const buttonEl =\n",
              "        document.querySelector('#id_312d31df-403c-4c06-b9e6-cea849ed32cf button.colab-df-generate');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      buttonEl.onclick = () => {\n",
              "        google.colab.notebook.generateWithVariable('df');\n",
              "      }\n",
              "      })();\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "df",
              "summary": "{\n  \"name\": \"df\",\n  \"rows\": 4,\n  \"fields\": [\n    {\n      \"column\": \"Marca\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 4,\n        \"samples\": [\n          \"RAM\",\n          \"Ferrari\",\n          \"Honda\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Modelo\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 4,\n        \"samples\": [\n          \"Dodge Ram\",\n          \"Ferrari\",\n          \"Civic\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Ano\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 3,\n        \"min\": 2016,\n        \"max\": 2023,\n        \"num_unique_values\": 4,\n        \"samples\": [\n          2023,\n          2020,\n          2022\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Avalia\\u00e7\\u00e3o (0-5)\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.35590260840104393,\n        \"min\": 4.1,\n        \"max\": 4.9,\n        \"num_unique_values\": 4,\n        \"samples\": [\n          4.6,\n          4.9,\n          4.8\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Acelera\\u00e7\\u00e3o (m/s\\u00b2)\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 3.3260336739125176,\n        \"min\": 2.0,\n        \"max\": 10.0,\n        \"num_unique_values\": 4,\n        \"samples\": [\n          5.0,\n          10.0,\n          6.5\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Tempo 0-100km/h (s)\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 4.974752925188011,\n        \"min\": 2.78,\n        \"max\": 13.89,\n        \"num_unique_values\": 4,\n        \"samples\": [\n          5.56,\n          2.78,\n          4.27\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Frenagem (m/s\\u00b2)\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 3.095695936834452,\n        \"min\": 6.0,\n        \"max\": 13.0,\n        \"num_unique_values\": 4,\n        \"samples\": [\n          7.0,\n          13.0,\n          9.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Tipo de Frenagem\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"ABS e freios a disco\",\n          \"Sistema ABS (dependendo da vers\\u00e3o)\",\n          \"Freios de alto desempenho\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Sistemas Auxiliares\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"Controle de estabilidade e assist\\u00eancia de frenagem\",\n          \"Controle de estabilidade (dependendo da vers\\u00e3o)\",\n          \"ABS, controle de estabilidade e assist\\u00eancia eletr\\u00f4nica\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Nota M\\u00e9dia C.B.\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.8421203397773187,\n        \"min\": 5.8,\n        \"max\": 7.8,\n        \"num_unique_values\": 4,\n        \"samples\": [\n          6.5,\n          5.8,\n          7.8\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Pre\\u00e7o (R$)\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1655236,\n        \"min\": 35000,\n        \"max\": 3500000,\n        \"num_unique_values\": 4,\n        \"samples\": [\n          450000,\n          3500000,\n          140000\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Custo-Benef\\u00edcio\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.9102383277654998,\n        \"min\": 0.0164,\n        \"max\": 2.0,\n        \"num_unique_values\": 4,\n        \"samples\": [\n          0.1444,\n          0.0164,\n          0.5536\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "=== RANKING DE CUSTO-BENEFÍCIO ===\n",
            "1º - Palio (CB: 2.0000 | Preço: R$ 35,000.00)\n",
            "2º - Civic (CB: 0.5536 | Preço: R$ 140,000.00)\n",
            "3º - Dodge Ram (CB: 0.1444 | Preço: R$ 450,000.00)\n",
            "4º - Ferrari (CB: 0.0164 | Preço: R$ 3,500,000.00)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [],
      "metadata": {
        "id": "LaAiK9joMXSt"
      }
    }
  ]
}
