{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMMyGNobWEDz4pkFvK+cOTe",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/galo132171/trabalho-inf-14-rpzd/blob/main/Mobilidade%20e%20seguran%C3%A7a(Izaque).py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "from abc import ABC, abstractmethod\n",
        "\n",
        "# 1. ABSTRAÇÃO: Classe abstrata que define o modelo genérico de um sistema veicular\n",
        "class SistemaVeicular(ABC):\n",
        "\n",
        "    @abstractmethod\n",
        "    def ligar_motor(self) -> None:\n",
        "        \"\"\"Contrato obrigatório para qualquer veículo.\"\"\"\n",
        "        pass\n",
        "\n",
        "    @abstractmethod\n",
        "    def selecionar_terreno(self, modo: str) -> None:\n",
        "        \"\"\"Contrato para alteração de terreno.\"\"\"\n",
        "        pass\n",
        "\n",
        "\n",
        "# 2. ENCAPSULAMENTO: Implementação concreta com restrição de acesso aos atributos\n",
        "class CarroSeguro(SistemaVeicular):\n",
        "    def __init__(self, modelo: str, chave_codificada: str):\n",
        "        self.modelo = modelo\n",
        "\n",
        "        # Atributos privados (encapsulados) - não devem ser alterados diretamente de fora\n",
        "        self.__chave_correta = chave_codificada\n",
        "        self.__alarme_ativo = True\n",
        "        self.__cinto_afivelado = False\n",
        "        self.__terreno_atual = \"Asfalto\"\n",
        "        self.__motor_ligado = False\n",
        "\n",
        "    # --- MÉTODOS PÚBLICOS (Interface de Uso) ---\n",
        "\n",
        "    def afivelar_cinto(self) -> None:\n",
        "        \"\"\"Interface pública para alterar o estado do cinto.\"\"\"\n",
        "        self.__cinto_afivelado = True\n",
        "        print(\"[Segurança] Cinto de segurança afivelado.\")\n",
        "\n",
        "    def desativar_alarme(self, chave: str) -> bool:\n",
        "        \"\"\"Encapsula a validação da chave antes de alterar o alarme.\"\"\"\n",
        "        if self.__validar_chave(chave):\n",
        "            self.__alarme_ativo = False\n",
        "            print(\"[Segurança] Alarme desativado com sucesso.\")\n",
        "            return True\n",
        "        else:\n",
        "            print(\"[Alerta] Chave incorreta! Disparando alarme antifurto!\")\n",
        "            return False\n",
        "\n",
        "    def ligar_motor(self) -> None:\n",
        "        \"\"\"Implementação da abstração com checagem de regras internas.\"\"\"\n",
        "        if not self.__cinto_afivelado:\n",
        "            print(\"[Bloqueio] Não é possível ligar: Cinto desatado.\")\n",
        "            return\n",
        "\n",
        "        if self.__alarme_ativo:\n",
        "            print(\"[Bloqueio] Não é possível ligar: Alarme antifurto ativado.\")\n",
        "            return\n",
        "\n",
        "        self.__motor_ligado = True\n",
        "        print(f\"[Motor] {self.modelo} ligado e pronto para rodar!\")\n",
        "\n",
        "    def selecionar_terreno(self, modo: str) -> None:\n",
        "        \"\"\"Implementação da abstração para controle de terreno.\"\"\"\n",
        "        terrenos_suportados = {\n",
        "            \"Asfalto\": \"Tração 2WD padrão.\",\n",
        "            \"Lama\": \"Tração 4x4 com bloqueio de diferencial.\",\n",
        "            \"Areia\": \"Controle de tração ajustado para deslizamento.\",\n",
        "            \"Rochas\": \"Reduzida ativada e suspensão elevada.\"\n",
        "        }\n",
        "\n",
        "        if modo in terrenos_suportados:\n",
        "            self.__terreno_atual = modo\n",
        "            print(f\"[Terreno] Modo alterado para '{modo}': {terrenos_suportados[modo]}\")\n",
        "        else:\n",
        "            print(f\"[Erro] Modo '{modo}' não suportado.\")\n",
        "\n",
        "    # --- MÉTODOS PRIVADOS (Regras de negócio internas) ---\n",
        "\n",
        "    def __validar_chave(self, chave: str) -> bool:\n",
        "        \"\"\"Método privado: a lógica de verificação fica oculta do usuário.\"\"\"\n",
        "        return chave == self.__chave_correta\n",
        "\n",
        "\n",
        "# --- DEMONSTRAÇÃO DE USO NO GOOGLE COLAB ---\n",
        "\n",
        "# Criando a instância do veículo com a chave cadastrada \"CHAVE-123\"\n",
        "carro = CarroSeguro(modelo=\"SUV Off-Road\", chave_codificada=\"CHAVE-123\")\n",
        "\n",
        "print(\"=== 1. Tentativa de ligar sem cumprir requisitos de segurança ===\")\n",
        "carro.ligar_motor()\n",
        "\n",
        "print(\"\\n=== 2. Uso correto da interface pública (Encapsulamento em ação) ===\")\n",
        "# Tentativa com chave errada\n",
        "carro.desativar_alarme(chave=\"CHAVE-ERRADA\")\n",
        "\n",
        "# Procedimento correto\n",
        "carro.desativar_alarme(chave=\"CHAVE-123\")\n",
        "carro.afivelar_cinto()\n",
        "carro.ligar_motor()\n",
        "\n",
        "print(\"\\n=== 3. Modificação de terrenos ===\")\n",
        "carro.selecionar_terreno(\"Lama\")\n",
        "carro.selecionar_terreno(\"Rochas\")"
      ],
      "metadata": {
        "id": "_K8VSGVZYSHx"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}